(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.ss4cjs_demo = function() {
	this.initialize();

	// timeline function:
	this.frame_0 = function() {
		this.photo1.visible = true;
		this.photo2.visible = false;
		this.photo3.visible = false;
		
		//local で動作させるためhitAreaを設定
		var hitArea = new createjs.Shape();
		var r = this.button1.getChildAt(0).sourceRect;
		hitArea.graphics.beginFill("#FFF").drawRect(0,0,r.width,r.height);
		this.button1.getChildAt(0).hitArea=hitArea;
		this.button2.getChildAt(0).hitArea=hitArea;
		this.button3.getChildAt(0).hitArea=hitArea;
		
		this.button1.onPress=function(){
			exportRoot.photo1.visible = true;
			exportRoot.photo2.visible = false;						
			exportRoot.photo3.visible = false;						
			stage.update();
		}
		
		this.button2.onPress=function(){
			exportRoot.photo1.visible = false;
			exportRoot.photo2.visible = true;						
			exportRoot.photo3.visible = false;						
			stage.update();
		}
		
		this.button3.onPress=function(){
			exportRoot.photo1.visible = false;
			exportRoot.photo2.visible = false;						
			exportRoot.photo3.visible = true;						
			stage.update();
		}
	}

	// button3
	this.button3 = new lib.button3();
	this.button3.setTransform(283,392,1,1,0,0,0,40,15);

	// button1
	this.button1 = new lib.button1();
	this.button1.setTransform(75,392,1,1,0,0,0,40,15);

	// button2
	this.button2 = new lib.button2();
	this.button2.setTransform(179,392,1,1,0,0,0,40,15);

	// title
	this.title = new lib.title();
	this.title.setTransform(114.7,19.3,1,1,0,0,0,78.2,6.5);

	// photo1
	this.photo1 = new lib.photo1();
	this.photo1.setTransform(277,200,1,1,0,0,0,240,160);

	// photo2
	this.photo2 = new lib.photo2();
	this.photo2.setTransform(277,200,1,1,0,0,0,240,159);

	// photo3
	this.photo3 = new lib.photo3();
	this.photo3.setTransform(277,200,1,1,0,0,0,240,160);

	this.addChild(this.photo3,this.photo2,this.photo1,this.title,this.button2,this.button1,this.button3);
	this.frame_0();
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(35,12.8,483,394.2);


// symbols:
(lib.btn1 = function() {
	this.sourceRect=new cjs.Rectangle(0,0,80,30);
    this.initialize(img.ss);

}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);


(lib.btn2 = function() {
	this.sourceRect=new cjs.Rectangle(0,30,80,30);
    this.initialize(img.ss);

}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);


(lib.btn3 = function() {
	this.sourceRect=new cjs.Rectangle(0,60,80,30);
    this.initialize(img.ss);

}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);


(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,481,321);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,481,319);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,481,320);


(lib.title = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMHgiQgDgNgBgNQAAgCgBAAIgCAAIgGABIgBAAQgPgDgGAAQgJAAgHACQgIACgFADQgFAEgCAFQgDAGAAAGQAAAGADAFQACAFAEAEQAEAEAHADQAGAEAJADQAHACAEABQAFADAEADQADADACACQAAAEAAAEQAAADAAADQgCACgDACQgDACgEABQgEABgFAAQgEAAgFgBQgFgCgFgDQgFgFgEgFQgFgGgCgHQgBgBgBAAIgBAAQgBABAAABIAAAAQAEAVAAAFQABACABABQAHADAIABQAJACAIAAQAKAAAIgDQAIgBAFgEQAGgEACgGQADgFAAgHQAAgHgCgEQgDgFgFgEQgEgFgGgEQgHgEgJgCIgNgFQgGgCgCgDQgDgCgCgDQgCgCAAgEQAAgDACgCQABgDADgBQADgDAEAAQAFgBAFAAQAEAAAFABQAFACAEADQAEAEAEAEQAEAFABAFQABABAAAAIACAAQABAAAAgBIAAAAAKwg+IgrAAQgBAAAAABQAAACABAAQAGAAACACQACABAAADIAABDQAAAGgBAFQAAADgCAEQgCAEgEAAQgCAAgCgBQgBgCAAgCQAAgBABgCQABgCAAgDQAAgEgCgCQgCgCgFAAQgEAAgDACQgCADAAAEQAAAEABADQABADAEADQADABADACQAFABAFAAQAIAAAGgCQAGgBAEgFQAEgDABgFQACgGAAgIIAAhAQAAgDACgBQACgCAHAAQABAAAAgCQAAgBgCAAIAAAAAJjgWQgFgEgGgDQgGgDgIAAQgHAAgHADQgGADgGAEQgEAFgEAIQgCAJAAAEQAAAIACAGQADAIAFAEQAFAFAGADQAFACALABQAGAAAFgBQAEgCAEgCQAFgCACgDQADgDABgFIAAAAQAAgBAAgBIgCgBQAAAAgBABQgDAGgGADQgFACgGAAQgEAAgEgBQgEgBgCgDQgEgEgCgEQgCgFgBgHIAvgDQACgBAAgDQAAgFgDgGQgCgGgEgFIAAAAAJPgWQADABACAEQADADABAFQABADAAAEIAAABQAAABgBAAIgdABIgBgCQAAgFABgFQABgFADgDQABgDADgBQADgBAEAAQADAAACACIAAAAAIbgaQAAgDgCAAIgPAAIAAgVQAAgDgBAAQgDAAgBACQgBAEgCAEQgDAEgEADQgDADgEACQgEACgDAAQgDABAAACIAAABQAAABACAAIAJAAIAAAtQAAAFABAEQACADADADQADACAEACQAEABAFAAQAGAAAFgDQAFgCADgEQABgBAAgBIgBgCIgBAAIAAABQgFADgFAAQgEAAgCgCQgDgDAAgGIAAgtIAPAAQACAAAAgCIAAAAAHFgEQgHACgIABQgIABgFABQgFACgEADQgDADgBAEQgCAEAAAFQAAAFABADQACADACADQADACAEABQADACAFAAQAFAAAKgDQADgBADgCQADgCACgDQAAAGAEACQADADAHAAQAFAAADgDQAFAAADgDQABgBAAgBIgBgBIgBgBIgBABQgCABgCAAQgDAAgBgCQgBgCAAgFIAAgcQAAgGgCgFQgCgGgDgDQgEgDgGgCQgFgDgJAAQgHAAgGADQgGABgEADQgEACgCAEQgCADAAAFQAAADACACQADADADAAQAEAAADgCQACgBAAgEQAAgCgBgCQgBgCAAgBQAAgEADgBQACgCAGAAQADAAADABQADABABADQACACACADQAAAFAAAFIAAAAAHHAWQgCADgEACQgEABgEAAQgFAAgDgCQgDgDAAgFQAAgGADgDQACgDAGgCQAEgBAKgCIAAAVAGGgWQgFgEgGgDQgGgDgIAAQgHAAgHADQgGADgFAEQgFAFgDAIQgDAJAAAEQAAAIACAGQADAIAEAEQAFAFAHADQAFACALABQAGAAAFgBQAFgCADgCQAFgCACgDQADgDABgFIAAAAQAAgBAAgBIgCgBQgBAAAAABQgDAGgGADQgGACgFAAQgFAAgDgBQgEgBgDgDQgDgEgCgEQgCgFgBgHIAvgDQACgBAAgDQAAgFgDgGQgCgGgEgFIAAAAAFhgTQACgDADgBQADgBAEAAQADAAACACQADABACAEQADADAAAFQACADAAAEIAAABQAAABgCAAIgcABIgBgCQAAgFABgFQABgFACgDIAAAAAExgTQABABACADQAAAEABAAQABACAFAAQADAAACgCQADgCAAgFQAAgGgFgDQgCgCgCgBQgDgCgDAAQgFAAgGADQgGACgEAFIAAgHQAAgCgBAAIgBAAQgPAEgMACQgBABAAACQAAAAACAAQAEAAACABQAAABAAADIAAAvQAAACgBABQgCACgEABQgCAAAAABQAAABACAAIAlAAQABAAAAgBQAAgBgBAAQgFgBgCgCQgBgBAAgCIAAgnQAAgDABgCQABgDACgBQAEgEAFAAQAEAAABADIAAAAADsg8QgDAAgDgBQgFgBgHgCIgMAAQgGAAgFABQgFABgFABQgFACgEAEQgEACgEAEQgDAEgCAEQgCAEgCAFQgCAFgBAFQgBAFAAAGQAAAGABAFQABAEACAFQACAFACAEQACAEAEAEQADAEAEACQAEADAFACQAFABAGACQAGABAGAAQAJAAAKgCQAJgCAGgDQADgBAAgBIABgaQAAgCgBAAQgCAAAAACQgDAIgDAGQgDAFgEADQgDAEgFABQgEABgFAAQgDAAgEgBQgDAAgDgCQgDgCgCgCQgEgCgBgEQgDgDgCgEQgCgFgBgEIgCgWQAAgKABgIQACgHAEgGQAEgFAFgCQAFgCAGAAQAGAAAFAAQAFACAEADQAEACAEAFQADAFADAHQABACABAAIABgBQABAAAAgBIgEgZQAAgCgBAAIgEAAACRAKQAAgDgCAAQAAgBgBAAIgRAAIAAhDQAAgCAAgBQgBAAgDAAQgEAAgCACIgzBAQgCADAAAEQAAAEAEAAIAlAAIAAARQAAACgDABQgCACgHABQgBAAAAABQAAABACAAIArAAQACAAAAgBQAAgBgBAAQgGgBgDgCQgCgBAAgCIAAgRIARAAQADAAAAgDIAAAAABngjQAAALgBAeIgfAAQAegmACgDIAAAAAAkgyQAAgDgCAAQgDAAAAACQgBAEgDAEQgCAEgFADQgDADgEACQgDACgEAAQgDABAAACIAAABQABABABAAIAKAAIAAAtQAAAFABAEQABADADADQADACAEACQAEABAGAAQAFAAAFgDQAFgCADgEQABgBAAgBIAAgCIgBAAIgBABQgEADgFAAQgFAAgCgCQgCgDAAgGIAAgtIAOAAQACAAAAgCQAAgDgCAAIgOAAIAAgVAgMgWQgEgEgGgDQgHgDgHAAQgIAAgHADQgGADgFAEQgFAFgDAIQgCAJAAAEQAAAIACAGQACAIAFAEQAFAFAHADQAFACALABQAGAAAFgBQAEgCAEgCQAEgCADgDQACgDACgFIAAAAQAAgBgBgBIgBgBQgBAAgBABQgDAGgGADQgFACgGAAQgEAAgDgBQgEgBgDgDQgDgEgCgEQgDgFgBgHIAwgDQABgBAAgDQAAgFgCgGQgCgGgFgFIAAAAAgwgTQACgDADgBQACgBAEAAQADAAADACQADABACAEQACADABAFQABADAAAEIAAABQAAABgBAAIgdABIAAgCQAAgFABgFQABgFACgDIAAAAAhxgWQADABACAEQACADABAFQABADAAAEIAAABQAAABgBAAIgdABIAAgCQAAgFABgFQABgFACgDQACgDADgBQADgBADAAQADAAADACIAAAAAhegWQgEgEgGgDQgGgDgIAAQgIAAgGADQgHADgFAEQgFAFgDAIQgCAJAAAEQAAAIACAGQACAIAFAEQAFAFAHADQAFACALABQAGAAAFgBQAEgCAEgCQAEgCADgDQACgDACgFIAAAAQAAgBgBgBIgBgBQgBAAgBABQgDAGgFADQgGACgFAAQgFAAgDgBQgEgBgDgDQgDgEgCgEQgCgFgBgHIAvgDQACgBAAgDQAAgFgDgGQgCgGgFgFIAAAAAikAlQAAgBgCAAQgEgBgBgCQgCgBAAgCIAAggQAAgHgCgGQgBgGgDgDQgDgEgFgBQgEgDgFAAQgHAAgGADQgGACgFAFIAAgoQAAgCgBAAIAAAAQgSAFgJACQgCAAAAABQABACABAAQAFAAABAAQABABAAADIAABQQAAACgBABQgCACgFABQgBAAAAABQAAABACAAIAjAAQABAAAAgBQAAgBgBAAQgEgBgBgBQgCgBAAgDIAAgsQADgDADgCQAEgCAEAAQACAAACACQACAAACADQACACABAFQABAEAAAFIAAAeQAAADgCAAQgBACgEABQgBAAAAABQAAABABAAIAjAAQACAAAAgBIAAAAAkOg8QgBgCgBAAIgCAAIgFABIgCAAQgOgDgHAAQgJAAgHACQgHACgFADQgFAEgCAFQgDAGAAAGQAAAGACAFQACAFAFAEQAEAEAHADQAGAEAJADQAGACAFABQAFADADADQADADACACQABAEAAAEQAAADgBADQgCACgDACQgCACgEABQgEABgGAAQgEAAgFgBQgFgCgEgDQgFgFgEgFQgFgGgDgHQAAgBgBAAIgBAAQgBABAAABIAAAAQADAVABAFQAAACACABQAGADAJABQAIACAIAAQALAAAIgDQAIgBAFgEQAFgEADgGQADgFAAgHQAAgHgDgEQgCgFgFgEQgEgFgHgEQgHgEgIgCIgNgFQgGgCgDgDQgDgCgCgDQgBgCAAgEQAAgDABgCQACgDADgBQACgDAEAAQAFgBAFAAQAFAAAFABQAEACAFADQAEAEADAEQAEAFACAFQABABAAAAIABAAQABAAAAgBIAAAAQgCgNgBgNIAAAAAl1gdQgGgDgHAAQgIAAgHADQgGADgFAEQgFAFgDAIQgDAJAAAEQAAAIADAGQACAIAFAEQAFAFAHADQAFACALABQAGAAAEgBQAFgCAEgCQAEgCADgDQACgDACgFIAAAAQAAgBgBgBIgBgBQgBAAgBABQgDAGgGADQgFACgGAAQgEAAgEgBQgDgBgDgDQgDgEgDgEQgCgFgBgHIAwgDQABgBAAgDQAAgFgCgGQgCgGgFgFQgEgEgHgDIAAAAAl0gBQAAABgBAAIgdABIAAgCQAAgFABgFQABgFACgDQACgDADgBQACgBAEAAQADAAADACQADABACAEQACADABAFQABADAAAEIAAABAnRgkQgEADgEACQgDACgEAAQgCABAAACIAAABQAAABACAAIAIAAIAAAtQAAAFACAEQACADACADQADACAFACQAEABAFAAQAGAAAEgDQAFgCAEgEQAAgBAAgBIAAgCIgBAAIgBABQgEADgFAAQgEAAgDgCQgCgDAAgGIAAgtIAOAAQACAAAAgCQAAgDgCAAIgOAAIAAgVQAAgDgCAAQgCAAgBACQgBAEgDAEQgDAEgDADIAAAAAn0g9QgEgDgFAAQgFAAgDADQgEAEAAAFQAAAFAEADQADAEAFAAQAFAAAEgEQADgDAAgFQAAgFgDgEIAAAAAoHgRIAAAvQAAADgCAAQgCACgFABQgBAAAAABQAAABABAAIAnAAQABAAAAgBQAAgBgBAAQgFgBgCgCQgCAAAAgDIAAg7QAAgDgBAAIAAAAQgSAGgKABQgBABAAABQAAABACAAQAFAAABABQABABAAADIAAAAAo5gdQAAgCgBAAIgBAAQgPAEgLACQgCABAAACQAAAAACAAQAFAAABABQABABAAADIAAAvQAAACgCABQgBACgFABQgBAAAAABQAAABABAAIAlAAQABAAAAgBQAAgBgBAAQgEgBgCgCQgCgBAAgCIAAgnQAAgDABgCQABgDACgBQAEgEAFAAQAEAAACADQABABABADQAAAEABAAQACACAEAAQAEAAACgCQACgCAAgFQAAgGgEgDQgCgCgDgBQgCgCgDAAQgGAAgGADQgFACgFAFIAAgHAppgVQgEgFgGgDQgGgDgHAAQgGAAgFADQgGADgDAEIAAgHQAAgCgBAAQgSAFgJABQgBABAAACQAAABABAAQAFAAABAAQABABAAADIAABJQAAADgCACQgBABgEABQgCAAAAAAQAAACACAAIAkAAQACAAAAgCQAAAAgCAAQgEgBgCgBQgCgCAAgDIAAgWQADADAFABQAFADAFAAQAIAAAGgDQAGgCAEgGQAEgEACgIQADgGAAgIQAAgGgCgHQgCgHgEgFIAAAAAqPgSQADgDADAAQAEAAAEACQADACACADQADAFACAFQABAFAAAJQAAAGgBAEQgBAFgCADQgCACgDABQgCACgEAAQgDAAgDgCQgCgBgCgDQgDgCgBgEQgBgEAAgFIAAgZQABgDAEgCIAAAAArLgsQADAFACAFQABABAAAAIABAAQABAAAAgBIAAAAQgCgNgBgNQgBgCgBAAIgBAAIgFABIgDAAQgOgDgHAAQgJAAgHACQgHACgFADQgFAEgCAFQgCAGAAAGQAAAGACAFQACAFAEAEQAEAEAHADQAGAEAJADQAHACAEABQAFADADADQADADACACQABAEAAAEQAAADgBADQgCACgCACQgDACgEABQgEABgGAAQgEAAgEgBQgFgCgFgDQgFgFgEgFQgFgGgDgHQAAgBgBAAIgBAAQgBABAAABIAAAAQAEAVAAAFQAAACACABQAGADAJABQAJACAIAAQAKAAAIgDQAIgBAFgEQAGgEACgGQADgFAAgHQAAgHgDgEQgCgFgFgEQgEgFgHgEQgGgEgJgCIgNgFQgFgCgEgDQgDgCgBgDQgCgCAAgEQAAgDACgCQABgDADgBQADgDAEAAQAEgBAGAAQAEAAAFABQAFACAEADQAEAEAEAEIAAAA").cp();
	this.shape.setTransform(78.2,6.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,156.3,13.1);


(lib.photo3 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.img3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,481,320);


(lib.photo2 = function() {
	this.initialize();

	// Layer 1
	this.instance_1 = new lib.img2();

	this.addChild(this.instance_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,481,319);


(lib.photo1 = function() {
	this.initialize();

	// Layer 1
	this.instance_2 = new lib.img1();

	this.addChild(this.instance_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,481,321);


(lib.button3 = function() {
	this.initialize();

	// Layer 1
	this.instance_3 = new lib.btn3();

	this.addChild(this.instance_3);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);


(lib.button2 = function() {
	this.initialize();

	// Layer 1
	this.instance_4 = new lib.btn2();

	this.addChild(this.instance_4);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);


(lib.button1 = function() {
	this.initialize();

	// Layer 1
	this.instance_5 = new lib.btn1();

	this.addChild(this.instance_5);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,30);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;